experiment_name: debug_config
n_repeats: 1
scenario_params_list:
 - dataset_name:
    'mnist':
    - 'init'
    - './experiments/debug_config_2020-06-17_11h26/scenario_1_repeat_1_2020-06-17_11h26_85f/model/mnist_final_weights.h5'
    'cifar10':
    - 'init'
   partners_count:
    - 3
   amounts_per_partner:
    - [0.2, 0.5, 0.3]
   samples_split_option:
    - ['advanced', [[4, 'shared'], [6, 'shared'], [4, 'specific']]]
   multi_partner_learning_approach:
    - 'fedavg'
   aggregation_weighting:
    - 'uniform'
   methods:
    - ["Shapley values", "Independent scores"]
   gradient_updates_per_pass_count:
    - 5
   is_quick_demo:
    - True
   dataset_proportion:
    - 1
   epoch_count:
    - 2
   minibatch_count:
    - 2
